<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<VersionPrefix>1.0.0-beta3</VersionPrefix>
		<Authors>The Orchard Core Contrib Team</Authors>
		<Company />
		<Description>Provides an implementation APIs for testing Orchard Core applications.</Description>
		<PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/OrchardCoreContrib/OrchardCoreContrib.Testing/tree/main/src/OrchardCoreContrib.Testing.UI/README.md</PackageProjectUrl>
		<RepositoryUrl>https://github.com/OrchardCoreContrib/OrchardCoreContrib.Testing</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PackageTags>Orchard Core, Orchard Core Contrib, Testing</PackageTags>
		<PackageReleaseNotes>https://github.com/OrchardCoreContrib/OrchardCoreContrib.Testing/releases</PackageReleaseNotes>
		<PackageId>OrchardCoreContrib.Testing</PackageId>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Product>Orchard Core Contrib Testing</Product>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Copyright>2019 Orchard Core Contrib</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Key="0024000004800000940000000602000000240000525341310004000001000100d55741af1ace56fdeef517b92910c651b1316c7dfd0e644f2a8f80ceadad9ee09ca26959e4335dc7dd9df3d31c334a3438fe11bc1d94c03447f8db36e129fd798b390d8d2d2afbb3a3cb9af854076981b389263f43910cb59bb0259c85e68d6a9a03b4383f7832c24910fea2b30aa67bb9696dc5a38b724778ea5d1966b12bd2" Include="OrchardCoreContrib.Testing.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="OrchardCore.Abstractions" />
		<PackageReference Include="OrchardCore.Infrastructure.Abstractions" />
		<PackageReference Include="OrchardCore.Tenants" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\images\icon.png" Pack="true" PackagePath="icon.png" />
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
