name: Orchard Core Contrib Testing - Build

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        token: ${{ secrets.OCC_TOKEN }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.*
          10.0.*

    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install Playwright.NET
      uses: phil-scott-78/setup-playwright-dotnet@v0.1.0-alpha
      with:
        with-deps: true
        browsers: 'all'

    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
